# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The New Zealand Sessions
email: admin@session.nz
description: > # this means to ignore newlines until "baseurl:"
  Website of the Irish sessions in New Zealand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://session.nz" # the base hostname & protocol for your site
facebook: https://www.facebook.com/groups/WellingtonSession
jekyll: https://jekyllrb.com
github: https://github.com/slow-session/session.nz

# Build settings
markdown: kramdown

collections:
  tunes:
    output: true

defaults:
  - scope:
        path: "_tunes"
    values:
        layout: "tunepage"
  - scope:
        path: "_tunes/comhaltas"
    values:
        mp3_licence: CC-BY-NC-2.5
        mp3_source: Comhaltas Ceoltóirí Éireann
  - scope:
        path: "_tunes/wellington-session"
    values:
        mp3_licence: CC-BY-NC-4.0
        mp3_source: Wellington Session
  - scope:
        path: "_tunes/ballyscully"
    values:
        mp3_licence: CC-BY-NC-4.0
        mp3_source: Ballyscully - used by permission
  - scope:
        path: "_tunes/ceol-aneas"
    values:
        mp3_licence: CC-BY-NC-4.0
        mp3_source: Ceol Aneas
  - scope:
        path: "_tunes/free-music-archive"
    values:
        mp3_licence: Attribution-Share Alike 3.0 United States License
        mp3_source: Free Music Archive
  - scope:
        path: "_tunes/50dundas"
    values:
        mp3_licence: CC-BY-NC-4.0
        mp3_source: 50Dundas
